FROM node:alpine
WORKDIR /opt/app
COPY ./package.json .
COPY ./yarn.lock .
RUN yarn install --frozen-lockfile
COPY ./maps/fusioncharts.poland.js ./node_modules/fusioncharts/maps
COPY . .
CMD ["yarn","start" ]
