export const voivodeships = [
  "dolnośląskie",
  "kujawsko-pomorskie",
  "lubelskie",
  "lubuskie",
  "łódzkie",
  "małopolskie",
  "mazowieckie",
  "opolskie",
  "podkarpackie",
  "podlaskie",
  "pomorskie",
  "śląskie",
  "świętokrzyskie",
  "warmińsko-mazurskie",
  "wielkopolskie",
  "zachodniopomorskie",
];

export const education = ["PODSTAWOWE", "ŚREDNIE", "WYŻSZE"];

export const marital = ["ŻONATY", "MĘŻATKA", "KAWALER", "PANNA"];

export const sex = ["F", "M"];

export const contractType = [
  "Kontrakt B2B",
  "Umowa o pracę",
  "Umowa zlecenie",
  "Umowa o dzieło",
  "Samozatrudnienie",
  "Wolontariat",
  "Inna forma umowy cywilnoprawnej",
  "Staż, praktyka",
  "Brak oficjalnej umowy",
];

export const currencies = ["PLN", "EUR", "USD", "Inne"];

export const familyType = [
  "DZIECKO",
  "MĄŻ/ŻONA",
  "RODZIC",
  "ZWIĄZEK NIEFORMALNY",
  "DZIADEK/BABCIA",
];

export const accomodationType = [
  "DOM JEDNORODZINNY",
  "DOM WIELORODZINNY",
  "MIESZKANIE W BLOKU",
  "INNE",
];

export const disability = [
  "BRAK",
  "LEKKI STOPIEŃ",
  "UMIARKOWANY STOPIEŃ",
  "ZNACZNY STOPIEŃ",
];

export const industryType = [
  "artykuły codziennego użytku",
  "artykuły elektryczne",
  "artykuły spożywcze i szybkozbywalne",
  "banki komercyjne",
  "biotechnologia",
  "biura podróży",
  "budownictwo",
  "budownictwo - pozostałe",
  "budownictwo ogólne",
  "budownictwo przemysłowe",
  "chemia i surowce",
  "chemia podstawowa",
  "chemia specjalistyczna",
  "chemikalia",
  "części samochodowe",
  "drewno",
  "dystrybucja leków",
  "dystrybucja paliw i gazu",
  "działalność inwestycyjna",
  "elektronika użytkowa",
  "energetyka",
  "energia odnawialna",
  "firmy ubezpieczeniowe",
  "giełdy i biura maklerskie",
  "gry",
  "górnictwo metali",
  "górnictwo węgla",
  "handel detaliczny",
  "handel hurtowy - pozostałe",
  "handel hurtowy -pozostałe",
  "handel internetowy",
  "hotele i restauracje",
  "hutnictwo metali nieżelaznych",
  "hutnictwo żelaza i stali",
  "informatyka - pozostałe",
  "instalacje budowlane i telekomunikacyjne",
  "inżynieria lądowa i wodna",
  "komputery i elektronika",
  "kosmetyki i chemia gospodarcza",
  "leasing i faktoring",
  "materiały budowlane",
  "meble i dywany",
  "media - pozostałe",
  "motoryzacja - pozostałe",
  "napoje",
  "nieruchomości - pozostałe",
  "nowe technologie",
  "odzież i kosmetyki - pozostałe",
  "odzież i obuwie",
  "oprogramowanie",
  "paliwa i gaz - pozostałe",
  "papier i opakowania",
  "portale internetowe",
  "pośrednictwo finansowe",
  "produkcja leków",
  "produkcja rolna i rybołówstwo",
  "przemysł materiałów budowlanych",
  "radio i telewizja",
  "recykling",
  "reklama i marketing",
  "rekreacja i wypoczynek - pozostałe",
  "rynek kapitałowy - pozostałe",
  "sprzedaż nieruchomości",
  "sprzęt elektryczny i elektroniczny",
  "sprzęt i materiały medyczne",
  "sprzęt informatyczny",
  "systemy informatyczne",
  "szpitale i przychodnie",
  "telekomunikacja",
  "transport",
  "transport i logistyka - pozostałe",
  "tworzywa sztuczne",
  "ubezpieczenia",
  "ubezpieczenia - pozostałe",
  "urządzenia elektryczne",
  "urządzenia mechaniczne",
  "usługi - inne",
  "usługi dla przedsiębiorstw",
  "wierzytelności",
  "wydawnictwa",
  "wydobycie i produkcja",
  "wynajem nieruchomości",
  "wyposażenie domu - pozostałe",
  "wyroby hutnicze",
  "wyroby metalowe",
  "zaopatrzenie - pozostałe",
  "zarządzanie aktywami",
  "środki transportu",
  "żywność",
];
